# ☕ Java 공부 기록

## 📘 학습 날짜
- 2025-06-21

## 📅 오늘 배운 내용

### ✨ 1. 예외 처리가 필요한 이유

반환 값을 통해 예외처리를 하는 방식은 정상흐름과 예외 흐름을 구분 짓기 어렵기 
때문에 예외처리 메커니즘 (try - catch - finally)를 통해 정상 흐름과 예외 흐름 명확하게 분리 가능 <br>

### 2. 예외 계층 
- Object : 자바에서 기본형 제외한 모든 것은 객체, 예외도 객체, 모든 객체의 최상위 부모는 Object
- Throwable : 최상위 예외 , 하위에 Exception과 Error존재
- Error : 시스템 오류 , 복구 불가능한 시스템 예외
- Exception 체크 예외 :  애플리케이션 로직에서 사용할 수 있는 실질적 최상위 예외<br> Exception과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외 단, RuntimeException은 예외
- RuntimeException : 언체크예외, 런타임 예외 , 컴파일러가 체크하지 않는 언체크 예외, 그 자식 예외 모두 언체크 예외

### 3. 예외 기본 규칙

예외는 발생 시 처리하거나 , 밖으로 던져야함

- 체크예외 : try -catch로 처리하지 못한다면 throws를 통해 밖으로 던져야함
- Exception을 catch로 잡으면 그 하위 예외들 모두 잡을 수 있음
- Exception을 throws로 던지면 그 하위 예외 모두 던질 수 있음
- 처리하지 못하고 계속 던진다면 main() 밖까지 던져지고, 예외 로그를 출력하면서 시스템 종료됨
- 언체크예외 :  컴파일러가 예외를 체크하지 않는다는 뜻, 체크예외와 달리 throws를 선언하지 않고 생략 가능. 자동으로 예외 던짐
- try 명령중 하나에서 예외가 터지면 바로 catch구문으로 넘어가서 예외처리 및 catch끝나면 바로 finally에 있는 명령 실행함.

### 4. 예외 처리를 실무에서는 어떻게 하는가? 및 예제

- 처리할 수 없는 예외: 예외를 잡아서 복구할 수 있는 예외보다 복구할 수 없는 예외가 더 많다.
- 체크 예외의 부담: 처리할 수 없는 예외는 밖으로 던져야 한다. 체크 예외이므로 throws에 던질 대상을 일일이 명시해야함. 

체크예외는 오래전부터 많이 사용되었지만 현재는 처리할 수 없는 예외가 많아지고, 프로그램이 점점 복잡해지면서 체크 예외 사용하는 것이 점점 더 부담스러워짐 <br>
즉 현재 실무에서는 언체크(런타임)예외 처리를 많이 사용하고, 예외를 공통으로 처리할 수 있는 곳을 만들어서 한 곳에서 해결한다. <br>
어차피 해결 할 수 없는 예외들이기에 고객에게 현재 시스템에 문제가 있다고 오류 메시지를 보여주고, 웹이라면 오류 페이지를 보여주면 된다. 그리고 내부 개발자가 문제 상황을 빠르게 인지할 수 있도록 오류에 대한 로그를 남겨놓는다.


```java
package exception.ex4;

import exception.ex4.exception.SendExceptionV4;

import java.util.Scanner;

public class MainV4 {

    public static void main(String[] args) {
        //NetworkServiceV4 networkService = new NetworkServiceV4();
        NetworkServiceV5 networkService = new NetworkServiceV5();

        Scanner scanner = new Scanner(System.in);
        while (true) {
            System.out.print("전송할 문자: ");
            String input = scanner.nextLine();
            if (input.equals("exit")) {
                break;
            }

            try {
                networkService.sendMessage(input);
            } catch (Exception e) {
                exceptionHandler(e);
            }
            System.out.println();
        }
        System.out.println("프로그램을 정상 종료합니다.");
    }

    //공통 예외 처리
    private static void exceptionHandler(Exception e) {
        //공통 처리
        System.out.println("사용자 메시지: 죄송합니다. 알 수 없는 문제가 발생했습니다.");
        System.out.println("==개발자용 디버깅 메시지==");
        e.printStackTrace(System.out); //스택 트레이스 출력
        //e.printStackTrace();

        //필요하면 예외 별로 별도의 추가 처리 가능
        if (e instanceof SendExceptionV4 sendEx) {
            System.out.println("[전송 오류] 전송 데이터: " + sendEx.getSendData());
        }
    }
}

```
```java
package exception.ex4;

import exception.ex4.exception.ConnectExceptionV4;
import exception.ex4.exception.SendExceptionV4;

public class NetworkClientV5 implements AutoCloseable {

    private final String address;
    public boolean connectError;
    public boolean sendError;

    public NetworkClientV5(String address) {
        this.address = address;
    }

    public void connect() {
        if (connectError) {
            throw new ConnectExceptionV4(address, address + " 서버 연결 실패");
        }
        //연결 성공
        System.out.println(address + " 서버 연결 성공");
    }

    public void send(String data) {
        if (sendError) {
            throw new SendExceptionV4(data, address + " 서버에 데이터 전송 실패: " + data);
            //throw new RuntimeException("ex");
        }
        //전송 성공
        System.out.println(address + " 서버에 데이터 전송: " + data);
    }

    public void disconnect() {
        System.out.println(address + " 서버 연결 해제");
    }

    public void initError(String data) {
        if (data.contains("error1")) {
            connectError = true;
        }
        if (data.contains("error2")) {
            sendError = true;
        }
    }

    @Override
    public void close() {
        System.out.println("NetworkClientV5.close");
        disconnect();
    }
}

```
```java
package exception.ex4;

public class NetworkServiceV5 {

    public void sendMessage(String data) {
        String address = "http://example.com";

        try (NetworkClientV5 client = new NetworkClientV5(address)) {
            client.initError(data); //추가
            client.connect();
            client.send(data);
        } catch (Exception e) {
            System.out.println("[예외 확인]: " + e.getMessage());
            throw e;
        }
    }
}

```
- try with resources를 사용하여 V5버전에서는 try가 끝나는 시점에 바로 close()가 호출된다.
- try with resources를 사용하지 않는 코드는 V4이다.
- 사용하지 않는다면, try 안에 명령을 실행하다가,  언체크 예외를 통해 예외를 밖으로 던지면 main()에서 catch로 예외를 핸들러로 보낸 뒤, finally에 있는 명령이 호출된다.

```java
package exception.ex4;

public class NetworkServiceV4 {

    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV4 client = new NetworkClientV4(address);
        client.initError(data); //추가

        try {
            client.connect();
            client.send(data);
        } finally {
            client.disconnect();
        }

    }
}

```
```java
package exception.ex4;

import exception.ex4.exception.ConnectExceptionV4;
import exception.ex4.exception.SendExceptionV4;

public class NetworkClientV4 {

    private final String address;
    public boolean connectError;
    public boolean sendError;

    public NetworkClientV4(String address) {
        this.address = address;
    }

    public void connect() {
        if (connectError) {
            throw new ConnectExceptionV4(address, address + " 서버 연결 실패");
        }
        //연결 성공
        System.out.println(address + " 서버 연결 성공");
    }

    public void send(String data) {
        if (sendError) {
            throw new SendExceptionV4(data, address + " 서버에 데이터 전송 실패: " + data);
            //throw new RuntimeException("ex");
        }
        //전송 성공
        System.out.println(address + " 서버에 데이터 전송: " + data);
    }

    public void disconnect() {
        System.out.println(address + " 서버 연결 해제");
    }

    public void initError(String data) {
        if (data.contains("error1")) {
            connectError = true;
        }
        if (data.contains("error2")) {
            sendError = true;
        }
    }
}

```

- 매일매일 꾸준히 -> 자바 중급 2편 + 백준 알고리즘 문제풀이